// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import { ERC20 } from "../../lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol";

// This is the testing token for unit test ONLY
// DO NOT EDIT THIS FILE incase any unexpected error
// DO NOT DEPLOY THIS CONTRACT for any on-chain testing
contract TestERC20 is ERC20("Test ERC20 Token", "TET") {
    constructor(uint256 supply) {
        _mint(msg.sender, supply);
    }

    function mintTo(address to, uint256 amount) public {
        _mint(to, amount);
    }

    function decimals() public pure override returns (uint8) {
        return 6;
    }
}
